#!/bin/bash

#. /usr/lib/nagios/plugins/host_info

nb_units=$(curl -s --unix-socket /mnt/ROOT/var/run/fleet.sock -H "Content-Type: application/json" -X GET http://localhost/fleet/v1/state | jq '{ state: .states[].systemdSubState }' | jq '.state' | sed 's/"//g' | wc -l)
running_units=$(curl -s --unix-socket /mnt/ROOT/var/run/fleet.sock -H "Content-Type: application/json" -X GET http://localhost/fleet/v1/state | jq '{ state: .states[].systemdSubState }' | jq '.state' | sed 's/"//g' | grep running | wc -l)

let "diff_units = $nb_units - $running_units"

if [ $diff_units -eq 0 ]; then
    echo "OK - No failing units.|FAILED=0"
    exit 0
elif [ $diff_units -eq 1 ]; then
    echo "WARNING - Failing units.|FAILED=1"
    exit 1
elif [ $diff_units -gt 1 ]; then
    echo "CRITICAL - Failing units.|FAILED=$diff_units"
    exit 2
else
    echo "UNKNOWN - Unexpected failed units count ($diff_units)"
    exit 3
fi
